### ISSUE TITLE
Alternative serialization API

### ISSUE THREAD

**Issue by itamarst** [ScatterHQ/eliot#224]
Right now ActionType/MessageType require setting up specific serializers for specific fields. One can imagine an alternate API which is "globally serialize messages of type X like so" and then you don't need to manually specify serializer each time.

```
# module 1
register_serializer(Dataset, lambda d: {"dataset_id": d.dataset_id, ...}

# module 2
LOG_MODIFY = ActionType("dataset:modify", fields(dataset=Dataset, param=int))

# module 3
LOG_DELETE = ActionType("dataset:delete", fields(dataset=Dataset))
```

Currently that would require creating a `Field` object and module 2 and 3 would need to import it or recreate logic.

**Comment by itamarst** [comment]
I'm finding this more necessary now that I'm using numpy with eliot. You end up with lots of unserializable `numpy.int64` and the like, very annoying.

**Comment by itamarst** [comment]
https://hynek.me/articles/serialization/ has interesting implementation idea.

**Comment by itamarst** [comment]
`bytes` are another thing that can't currently be logged. Which... perhaps is legit.

**Comment by itamarst** [comment]
@jonathanj pointed out the issues with having different libraries register different serializers. For that matter, a non-JSON destination mght want different serialization. So really this should be application specific, and destination specific:

```python
eliot.add_destination(FileDestination(sys.stdout), adapters={numpy.integers: int})
```

**Comment by itamarst** [comment]
Even better idea, just pass in custom JSONEncoder class.

**Comment by itamarst** [comment]
@jonathanj what do you think of https://github.com/ScatterHQ/eliot/commit/b71fe842eff7d28f03015787bb78da36ce497b30#diff-ee588fba5b39cd032edff035addfe0dcR42?

**Comment by jonathanj** [comment]
I think this is a better approach than the original suggestion. 👍
