### ISSUE TITLE
Library code for redirecting Eliot logs into Twisted

### ISSUE THREAD

**Issue by glyph** [ScatterHQ/eliot#269]
I already have a log destination configured (because I am using `twisted.logger`, and `twist`, et. al. already set up logging so I can see logs).

I don't particularly want to use Eliot, but some of the libraries I am using use it.

I don't understand why `redirectLogsForTrial` isn't just `redirectLogs`.  Would fixing this be the right way to go about it?  Its name suggests that the fact that it breaks when not run under trial is intentional, but I don't see any reason that would be desirable.

If this could be set up by default it would automatically fix #260 which might be a nice bonus.

**Comment by itamarst** [comment]
It... couldn't be setup by default insofar as Twisted is only an optional dependency of Eliot. I'll see about this next time I have a bit of time for open source.

**Comment by glyph** [comment]
It would certainly be possible to direct logs to Twisted if Twisted is importable and logs aren't going anywhere else; redirecting elsewhere can easily point them away from Twisted if nobody shows up to start the `globalLogBeginner`.

**Comment by itamarst** [comment]
I'll think about it. Should have some time for coding in a week or two, so will tackle this then.

**Comment by glyph** [comment]
That would be fantastic! I didn't really expect you to get to it until I had a patch of some kind ready, so this would be quite a bonus :).

**Comment by glyph** [comment]
Bump.  (Just reminding you that it's been "a week or two", but if you do not in fact have time then nevermind :)).
