### ISSUE TITLE
It's hard to track down the cause of some validation errors due to JSON encoding issues

### ISSUE THREAD

**Issue by exarkun** [ScatterHQ/eliot#278]
I've just had to debug a test failure around this traceback:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: testtools.testresult.real._StringException: Empty attachments:
  eliot-log

Traceback (most recent call last):
  File "/home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/eliot/_output.py", line 309, in validate
    fast_json.dumps(dictionary)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Certificate(PEM string with SHA-1 digest '077ffe8a0213c020aaefd5d5f8d0e5b31e40f3e0')> is not JSON serializable


lae_automation.test.test_subscription_manager.SubscriptionManagerTests.test_round_trip
-------------------------------------------------------------------------------
```

The only two pieces of identifying information here are the name of the failing test and the fact that there's a `Certificate` of some sort involved.  It would be nice to know more about the Eliot message for which the validation fails.  For example, the `action_type` is a big clue.  I ended up hacking my local Eliot to print out the whole message before raising this exception so that I could figure out where the offending code was.

This is similar to, but distinct from, #159.

**Comment by itamarst** [comment]
Thanks for the bug report. Will get to it next time I have a little time to work on Eliot (might be using it at work!). Alternatively it's probably an easy patch if you want to submit one.
