### ISSUE TITLE
Better support path

### ISSUE THREAD

**Issue by itamarst** [ScatterHQ/eliot#291]
IRC is problematic, since people aren't always around. Encourage people to file issues? Gitter, which has email notifications of later replies?

**Comment by jonathanj** [comment]
My vote is Github issues, I think a forum might be better suited but more effort to deploy and maintain. Github issues are more readily indexed by Google and the topic of conversation per issue is more focused than the general Gitter firehose, which means linking to/between them is more meaningful.

Personally, don't hang around on Gitter, which one would have to do to pick up new queries as opposed to watching a Github repo.
