### ISSUE TITLE
 logstash config in docs out of date

### ISSUE THREAD

**Issue by rueberger** [ScatterHQ/eliot#302]
Hi there - great work with this lib. Just discovered it and it's changing my life. 

Also just getting started with the whole ELK thing, logstash 6.2.2 doesn't like the example config in the docs, crashes. The options for the elasticsearch output plugin appear to have changed drastically https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html. 

Any ideas on what might work now?

**Comment by rueberger** [comment]
This filter seems to do the trick:

```
filter {
  json {
    source => "message"
  }
}
```

But what I'm still missing is how I can take advantage of the nice tree structure afforded by eliot in kibana

**Comment by itamarst** [comment]
I'll fix the docs, thanks.

The Kibana UI lets you sort columns. Typical pattern I've done is:

1. Find all messages with specific `task_uuid`.
2. Sort by `task_level`. Depending on version of Kibana/ES this is more or less tricky, basically as long as it realizes it's a list of integers it should do the right thing. If it decides it's a strings or something it messes up.

If you succeed at sorting, the result is visually like a tree.

**Comment by itamarst** [comment]
What's your use case for Eliot, by the way? I.e. what kind of application?

**Comment by rueberger** [comment]
Thanks for the tip I'll have to give that a try - I'll report back to this issue if I figure out something good.  Also I should add that the filter above only parses logs produced by `Message`, one would need to add filters for all used action types to capture those as well.  

This is for a data munging app.
