### ISSUE TITLE
No syntax highlighting on readthedocs

### ISSUE THREAD

**Issue by apnewberry** [ScatterHQ/eliot#307]
https://eliot.readthedocs.io/en/1.3.0/generating/types.html

![image](https://user-images.githubusercontent.com/31109952/41317368-d614c7c4-6e49-11e8-9da4-eecca4d3388e.png)
But it works on github
https://github.com/ScatterHQ/eliot/blob/e5bf9ef81ecef474803786575e9dafa6b40a4d65/docs/source/generating/types.rst#using-types-to-structure-messages-and-actions

![image](https://user-images.githubusercontent.com/31109952/41317414-f84328fe-6e49-11e8-8f38-4d0017773550.png)

**Comment by itamarst** [comment]
Thanks for the bug report, I'll investigate.

**Comment by itamarst** [comment]
Seems like this has something to do with a bug in RTD itself; hopefully this'll be fixed when I do a new release.

**Comment by itamarst** [comment]
Yeah, rebuilt docs on RTD and it's fixed. Thanks for reporting this!
