### ISSUE TITLE
Utility of some sort to view the tree structure of Eliot log messages

### ISSUE THREAD

**Issue by itamarst** [ScatterHQ/eliot#65]
Web UI? command-line tool? In any case useful to understand what's going on.

**Comment by jml** [comment]
https://github.com/jonathanj/eliottree / https://warehouse.python.org/project/eliot-tree/ is an external tool that helps with this.

**Comment by itamarst** [comment]
Yeah, probably can close this by just updating docs to link to that.

**Comment by itamarst** [comment]
Docs mention this now.
